- src/components/views/mine-ansatte/PhaseCard.tsx
- src/components/views/mine-ansatte/UserRow.tsx
- src/pages/mine-ansatte/[slug].tsx
Flyttet komponenter over til egne filer og byttet til ServerSideProps
> refactor(My Employees): Flyttet komponenter over til filer

- src/components/views/ansatt/Phase.tsx
- src/components/views/ansatt/TaskRow.tsx
- src/pages/ansatt/[id].tsx
> fix(Align): Fixed alignment in employee page

- package.json
- src/components/Avatar.tsx
- src/components/views/mine-oppgaver/TimeSection.tsx
- src/pages/mine-oppgaver.tsx
- yarn.lock
The two next months after the current will be displayed.
The avatar has also been updated
> feat(Month): Added two next months on my tasks

- __tests__/employee.test.ts
- __tests__/employeeTask.test.ts
- __tests__/phases.test.ts
- __tests__/professions.test.ts
- __tests__/tags.test.ts
- __tests__/task.test.ts
- package.json
- src/pages/api/employeeTasks/[id].tsx
- src/pages/api/employees.tsx
- src/pages/api/phases.tsx
- src/pages/api/phases/[phase_id].tsx
- src/pages/api/professions.tsx
- src/pages/api/tags.tsx
- src/pages/api/tasks.tsx
- src/pages/api/tasks/[task_id].tsx
- yarn.lock
> refactor(statuscodes): refactores

- src/components/InfoModal.tsx
> fix(fontSize): Updated description font size

- package.json
- src/components/Sidebar.tsx
- src/pages/api/employee/[id].tsx
- src/pages/api/employee/[id]/notifications.tsx
- yarn.lock
> feat(Load notif): Load notifications

- src/components/views/mine-oppgaver/TaskRow.tsx
- src/components/views/mine-oppgaver/TimeSection.tsx
- src/pages/mine-oppgaver.tsx
> feat(my_tasks): show expired tasks

- src/components/Modal.tsx
- src/components/Sidebar.tsx
- src/components/form/ToggleButtonGroup.tsx
- src/components/views/ansatt/Phase.tsx
- src/components/views/mine-ansatte/PhaseCard.tsx
- src/components/views/mine-oppgaver/TaskRow.tsx
- src/pages/ansatt/[id].tsx
- src/pages/api/cron/phases.ts
- src/scheduled.ts
- Fix H1 in H2 error in modal
- Just fetch for notifications when opening notificaitons
- wrap professions in task creator
- Add TableBody in Table
- Make cronjob a post request
- Only first phase show "ansvarlig"-text  in "Ansatt"-view
- Make title noWrap in "Mine Oppgaver"-view
> fix: fix several bugs, visual issues and console errors

- src/components/Sidebar.tsx
- src/pages/ansatt/[id].tsx
> feat(ActiveLink): Added color to active link

- src/components/views/ansatt/ChangeDueDateModal.tsx
Når man for eksempel skriv inn 01.04.2021 som dato ble denne gjort om til 31.03.2021 av moment, men jeg la til en fiks på dette.
> fix(datebug): Fixed datebug when update duedate

- package.json
- src/components/InfoModal.tsx
- src/components/Layout.tsx
- src/components/Sidebar.tsx
- src/components/form/EmployeeSelector.tsx
- src/context/User.tsx
- src/lib/withAuth.ts
- src/pages/alle-oppgaver.tsx
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/employee/[id].tsx
- src/pages/api/employee/[id]/notifications.tsx
- src/pages/api/employee/[id]/settings.tsx
- src/pages/api/employeeTasks/[id].ts
- src/pages/api/employees.ts
- src/pages/innstillinger.tsx
- src/pages/mine-oppgaver.tsx
- src/prisma/schema.prisma
- src/utils/types.ts
- yarn.lock
> feat(settings): add settings page and other chores

- src/components/views/ansatt/Phase.tsx
- src/components/views/ansatt/TaskModal.tsx
- src/pages/ansatt/[id].tsx
- src/pages/api/employeeTasks.ts
- yarn.lock
Modalen vil opprette en oppgave med global false før den deretter oppretter en employeeTask knyttet til den nylige opprettede tasken. Har kun med relevante felter det vil si at for eksempel yrker utgår og blir sendt som en tom array.
> feat(individualTasks): Added feature

- src/components/views/ansatt/Phase.tsx
- src/components/views/ansatt/TaskRow.tsx
- src/pages/ansatt/[id].tsx
Fikset noen feilmeldinger som dukket opp
> fi(warning): Fixed warnings and errors

- src/components/views/mine-ansatte/UserRow.tsx
- src/fixtures/employee1.yml
- src/fixtures/employee2.yml
- src/pages/alle-ansatte/[slug].tsx
- src/pages/mine-ansatte/[slug].tsx
> feat(Images): Updated fixtures with images and updated myEmployees

- src/components/form/EmployeeSelector.tsx
- src/components/views/mine-ansatte/UserRow.tsx
- src/components/views/mine-oppgaver/TaskRow.tsx
- src/pages/alle-ansatte/[slug].tsx
- src/pages/alle-oppgaver.tsx
- src/pages/api/cron/phases.ts
- src/pages/mine-ansatte/[slug].tsx
- src/pages/mine-oppgaver.tsx
- src/prisma/schema.prisma
- src/utils/types.ts
Oppdatert slik at oppgavene i kvartalet opprettes kvartalsvis, og ikke tar hensyn til om de er blitt fullført eller ikke.
> feat(Update): Tested and everything works

- src/pages/alle-ansatte/[slug].tsx
- src/pages/api/cron/phases.ts
- src/pages/mine-ansatte/[slug].tsx
Følgende har blitt gjort:
- Oppgaver blir opprettet kvartalsvis (en uke før kvartalet starter)
- Dersom alle oppgaver i en fase tilknyttet en ansatt er blitt gjort, men vi fortsatt er i det kvartalet vil den ansatte forbli på listen. Når vi så beveger oss inn i ny fase vil oppgaven ha blitt opprettet, og den ansatte flyttes det kvartalet. 
- På onboarding og offboarding vil det forbli det samme som det alltid har vært
> fix(EmployeeBug): Fixed bug

- src/components/InfoModal.tsx
- src/pages/api/employeeTasks/[id].ts
- src/prisma/schema.prisma
- src/utils/types.ts
Lagt til attributer i entiteten. I tillegg har endepunktene blitt oppdatert. 
Oppdatert frontend.
> feat(CompletedBy): Added attributes and updated frontend

- src/fixtures/employeeTask.yml
Oppdatert employeeTask sine forfallsdato (kvartal 1) som var satt til 31.05, og ikke 31.03
> feat(update): Fixtures

- package.json
- src/components/views/prosessmal/PhaseModal.tsx
- yarn.lock
Updated so that is does not longer display the year. 
Antall dager oppdateres også etter hvilken måned man har valgt.
> reafctor(Update): Updated day and month picker

- src/components/views/ansatt/TaskRow.tsx
- src/components/views/mine-oppgaver/TaskRow.tsx
> Feat(Updated names to not display lastname

- src/components/views/mine-ansatte/Filter.tsx
- src/components/views/mine-oppgaver/Filter.tsx
- src/theme.tsx
Fixed so that all contrast are good according to WCAG (2.1)
> fix(Contrast): Fixed contrast WCAG

- src/components/InfoModal.tsx
- src/components/LogIn.tsx
- src/components/views/ansatt/TaskModal.tsx
- src/components/views/ansatt/TaskRow.tsx
- src/components/views/mine-ansatte/PhaseCard.tsx
- src/components/views/mine-ansatte/UserRow.tsx
- src/components/views/mine-oppgaver/TaskRow.tsx
- src/components/views/mine-oppgaver/TimeSection.tsx
- src/components/views/prosessmal/Phase.tsx
- src/components/views/prosessmal/PhaseModal.tsx
- src/components/views/prosessmal/TaskModal.tsx
- src/components/views/prosessmal/TaskRow.tsx
- src/pages/ansatt/[id].tsx
Oppdatert så skjermleser er good
> feat(Aria labels): Updated aria labels

- src/components/form/BeforeToggle.tsx
- src/components/views/prosessmal/PhaseModal.tsx
- src/theme.tsx
> fix(DueDateInput): Fixed
